"""
This is the example script for working with the module random. This module
generates pseudo-random numbers with the help of different methods. I will show
your four of these methods here
"""
# First we import the module
import random

# Now I generate my random numbers
random_number1 = random.randint(0, 100)  # a random integer in the range 0 to 99
random_number2 = random.random()  # a random float in the range 0 to 1
# a random value from a normal distribution with mu=1 and sigma=5
random_number3 = random.gauss(1, 5)
# Now we print out oru random numbers
print("Generated by randint:", random_number1)
print("Generated by random:", random_number2)
print("Generated by gauss:", random_number3)
# Furthermore I create a list with a random length, by using randint and handing
# over the returned integer to the range generator and than casting it to a list
random_list1 = list(range(random.randint(0, 100)))
print("My random list before shuffle:\n", random_list1)
# Now I can use shuffle to mix up the order of the elements in my list. This
# method works in place just as our list methods did, so we make permanent
# changes to the list here.
random.shuffle(random_list1)
print("My random list after shuffle:\n", random_list1)
